feat: email verification and password reset
EduOJ/frontend pull request #9
Opened 2022-02-26 12:41 UTC by littlebear0729

First of all, thank you for your contribution! 😄

Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

### 这个变动的性质是

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [ ] 文档改进
- [ ] 组件样式改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 需求背景

> 1. 描述相关需求的来源。
> 2. 要解决的问题。
> 3. 相关的 issue 讨论链接。

### 实现方案和 API（非新功能可选）

> 1. 基本的解决思路和其他可选方案。
> 2. 列出最终的 API 实现和用法。
> 3. 涉及UI/交互变动需要有截图或 GIF。

### 对用户的影响和可能的风险（非新功能可选）

> 1. 这个改动对用户端是否有影响？影响的方面有哪些？
> 2. 是否有可能隐含的 break change 和其他风险？

### Changelog 描述（非新功能可选）

> 1. 英文描述
> 2. 中文描述（可选）

### 请求合并前的自查清单

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] Changelog 已提供或无须提供

### 后续计划（非新功能可选）

> 如果这个提交后面还有相关的其他提交和跟进信息，可以写在这里。

2022-02-26 12:44 UTC, littlebear0729 commented on src/config/router.config.js
> -            meta: { title: '个人设置', hideHeader: true },
This option is useless

2022-02-26 12:46 UTC, littlebear0729 commented on src/views/user/Login.vue
> +            >重置密码</router-link>
Show password reset option while wrong password login attempt occurred.

Need more investigation.

2022-03-01 03:06 UTC, leoleoasd requested changes

2022-03-01 03:06 UTC, leoleoasd commented on src/views/user/EmailVerify.vue
> +  mounted () {
这个没用 可以删掉

这个是，update me里，表格中预置的初始信息。

2022-03-01 03:06 UTC, leoleoasd commented on src/views/user/EmailVerify.vue
> +      const timer = setInterval(function () {
用箭头函数， `() => {}`，不需要that

2022-03-01 03:06 UTC, leoleoasd commented on src/views/user/EmailVerify.vue
> +          :disabled="verifyEmailBtn"
loading会自动disabled

2022-03-01 03:06 UTC, leoleoasd commented on src/views/user/EmailVerify.vue
> +            this.$success({
取消verifyEmailBtn要放在这里

2022-03-01 03:06 UTC, leoleoasd commented on src/views/user/ResetPassword.vue
> +            this.$success({
doResetPasswordBtn 放到这里

以及建议名字里加上loading

2022-03-05 11:27 UTC, merged